### ISSUE TITLE
Undefined bundle: "sep_crunch" 

### ISSUE THREAD

**Issue by pirapira** [pirapira/eth-isabelle#436]
`make` shows:

```
*** Failed to load theory "SimpleWallet" (unresolved "HoareTripleForLogGasCall")
*** Undefined bundle: "sep_crunch" (line 8 of "~/yoichi/eth-isabelle/Hoare/HoareTripleForLogGasCall.thy")
*** At command "context" (line 7 of "~/yoichi/eth-isabelle/Hoare/HoareTripleForLogGasCall.thy")
```

**Comment by pirapira** [comment]
@seed are you currently working on this?

**Comment by seed** [comment]
Yeah working on getting HoareTripleForInstruction.thy cleaned up and
HoareTripleForInstruction2.thy working too.
I'll look at SimpleWallet next.

I'm also trying to document the change I'm making and why I'm making them,
so that hopefully no one will have to do that again in the future :)

I'm hoping to finish this this weekend.

**Comment by pirapira** [comment]
I'll try again and close this issue.

**Comment by pirapira** [comment]
I cannot reproduce this error anymore.
